export enum NotificationType {
  LIKE = 'LIKE',
  COMMENT = 'COMMENT',
  FOLLOW = 'FOLLOW',
  PROJECT_BID = 'PROJECT_BID',
  PROJECT_ASSIGNED = 'PROJECT_ASSIGNED',
  PROJECT_COMPLETED = 'PROJECT_COMPLETED',
  MESSAGE = 'MESSAGE',
  SYSTEM = 'SYSTEM',
}